name: plmnist
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - numpy=1.24.0
  - pytorch::pytorch
  - pytorch::torchvision
  - pytorch::pytorch-cuda=12.1
  - conda-forge::pytorch-lightning
  - conda-forge::matplotlib
  - pip:
    - ray[tune]
    - hyperopt
    - tensorboard
    - -e .