name: plmnist
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.11
  - numpy=1.24.0
  - pytorch::pytorch
  - pytorch::torchvision
  - conda-forge::pytorch-lightning
  - conda-forge::matplotlib
  - conda-forge::signac
  - conda-forge::signac-flow
  - conda-forge::signac-dashboard